# Generated by Django 3.0.4 on 2020-04-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20200401_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
